spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/testDB
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port : 9090
